### ISSUE TITLE
Number of mesh cells per quadrant? 

### ISSUE THREAD

**Issue by donnaaboise** [GEM3D/pressurePoissonSolver#4]
I've added a new Wiki page [here](https://github.com/GEM3D/pressurePoissonSolver/wiki/Mesh-used-for-timing-results) describing the characteristics of the mesh we are using for timing results.  

Do we really want mesh sizes 128x128, 256x256 and 512x512?    Since Brenton was running into memory issues on the Div 4 mesh, maybe we should cut down the mesh size to 32x32, 64x64,128x128?   I would have thought in any case, that these are more reasonable mesh sizes.

**Comment by gradywright** [comment]
I think the choice of the higher resolution meshes was to test the scalability of the code.  I agree that in practice the smaller meshes will be used.

**Comment by isenocak** [comment]
Each AMR block (not to be confused with cuda block) of the octree does not have to be a huge mesh. In CUDA or OpenACC, the recommended practice for work load is to have multiple of the half-warp size, which is 16. So each AMR block does not have to be huge. 64x64 would be fine.

**Comment by donnaaboise** [comment]
I reserve "block" (at least in the AMR context) to mean a single quadtree.  Multi-block would be a mesh involving several quadtrees (for non-square domains, for example).      The 'quadrant' is simply the spatial placeholder for a grid,  i.e.  "grids occupy quadrants".    Quadrants at level L are have dimensions 2^(-L) times the level 0 quadrant.  Each grid is a fixed size, i.e. 16x16, 32x32, etc.   I use "mesh" to mean quadrants + grids, i.e. "the  mesh has 2.1 million degrees of freedom".

**Comment by donnaaboise** [comment]
As far as scaling goes, then, should we work with a mesh with more quadrants?

**Comment by donnaaboise** [comment]
Some **clarification** :  We are not creating blocks of sizes 128x128, 256x256 or 512x512.  But rather each quadrant in the adaptive mesh (shown in the wiki) contains a 1x1, 2x2, 3x3, etc array fo 32x32 grids.  So in the  "div 0" mesh, each quadrant contains a 32x32 grid.  In the "div 1" mesh, each quadrant contains 4 (in a 2x2 array) 32x32 grids.   Each quadrants in the  "div N" mesh contains an NxN array of 32x32 grids.  

The end result is that our scaling studies have been done on meshes with 2080 quadrants, 8320 quadrants and 33280  quadrants, each with a 32x32 grid.  

See this [wiki page](https://github.com/GEM3D/pressurePoissonSolver/wiki/Mesh-used-for-timing-results) for more details.
